schemaVersion: 2.2.2
metadata:
  name: opencode-devspace
components:
  - name: opencode-container
    container:
      image: registry.redhat.io/devspaces/udi-rhel9:3.29
      memoryLimit: '3Gi'
      memoryRequest: '2Gi'
      cpuLimit: '4'
      cpuRequest: '1'
      mountSources: true
      env:
        - name: OPCODE_SERVICE_URL
          value: 'http://redhataiqwen3-coder-next-nvfp4-predictor.coder.svc.cluster.local:8080/v1'
      command: ['bash', '-c', 'curl -fsSL https://opencode.ai/install | bash && tail -f /dev/null']
      volumeMounts:
        - name: opencode-volume
          path: /home/user/.opencode
  - name: opencode-volume
    volume:
      size: 1G
